#define NUM_MONSTERS 55
#define NUM_BULLETS 5
#define GAME_NUM_DRAWABLE_OBJECTS (NUM_MONSTERS + NUM_BULLETS + 1)

#define MENU_NUM_OPTIONS 3
#define MENU_NUM_DRAWABLE_OBJECTS (MENU_NUM_OPTIONS + 2)

#define GAMEOVER_OPTIONS 2
#define GAMEOVER_NUM_DRAWABLE_OBJECTS (GAMEOVER_OPTIONS + 3)
